import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NotificacionesSonido from "./NotificacionesSonido";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotificacionesSonido />
        <nav className="bg-white shadow p-4 flex gap-6 mb-8">
          <Link
            href="/"
            className="font-bold text-blue-700 hover:underline"
          >
            Comprar Café
          </Link>
          <Link
            href="/clientes"
            className="font-bold text-blue-700 hover:underline"
          >
            ABM Clientes
          </Link>
          <Link
            href="/pedidos"
            className="font-bold text-blue-700 hover:underline"
          >
            Ver Pedidos
          </Link>
          <Link
            href="/productos"
            className="font-bold text-blue-700 hover:underline"
          >
            ABM Productos
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
